packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  electron: true
  electron-native-screenshare: false
  electron-winstaller: true
  esbuild: true
  mediasoup: true
  sharp: true
  unrs-resolver: true

overrides:
  '@types/node': '^22.10.0'
