#!/usr/bin/env python3
"""Generate chapters/A0-appendix-a.md («Додаток А Лістинг програми») verbatim from the pinned commit.

Code is read with `git show <COMMIT>:<path>`, so the appendix always matches the commit named in its
intro sentence (application code on `diploma` is identical to that commit). Omitted line ranges are
marked `// ...` (PLAN.md §1.9). Long lines are kept verbatim; Word wraps them.

Usage (from anywhere inside the repo):
  python3 thesis/tools/appendix.py          # rewrite chapters/A0-appendix-a.md
  python3 thesis/tools/appendix.py --check  # exit 1 if the file is stale
"""
import subprocess
import sys
from pathlib import Path

COMMIT = "7c2f481"
THESIS = Path(__file__).resolve().parent.parent
OUT = THESIS / "chapters" / "A0-appendix-a.md"

# (id, language, path, line ranges (1-based, inclusive) or None for the whole file, caption)
LISTINGS = [
    ("lst:a-source-follower", "ts", "apps/desktop/src/main/sourceFollower.ts", None,
     "Клас SourceFollower настільного застосунку"),
    ("lst:a-mediasoup", "ts", "apps/signaling/src/services/mediasoup.service.ts", None,
     "Клас MediasoupService сервера сигналізації"),
    ("lst:a-streams-ws", "ts", "apps/signaling/src/controllers/streams.controller.ts",
     [(66, 97), (239, 519)],
     "Маршрути та обробники WebSocket класу StreamsController (фрагмент)"),
    ("lst:a-use-streamer", "ts", "apps/web/src/lib/hooks/useStreamer.ts",
     [(1, 56), (81, 148), (331, 407), (486, 492)],
     "Хук useStreamer сторінки трансляції (скорочено)"),
    ("lst:a-google-auth", "ts", "apps/desktop/src/main/googleAuth.ts", None,
     "Вхід через Google у системному браузері в настільному застосунку"),
]

INTRO = f"""# Додаток А Лістинг програми

<!-- Generated by thesis/tools/appendix.py from commit {COMMIT}. Do not edit by hand. -->

У додатку наведено вихідний код ключових модулів програмної системи stream-share у стані фіксації
`{COMMIT}` репозиторію. Пропущені фрагменти позначено коментарем `// ...`. Вихідні тексти всіх
діаграм PlantUML, наведених у роботі, зберігаються в каталозі `thesis/diagrams` репозиторію поруч
із відповідними зображеннями.
"""


def source(path: str) -> list[str]:
    out = subprocess.run(["git", "show", f"{COMMIT}:{path}"], cwd=THESIS, check=True,
                         capture_output=True, text=True).stdout
    return out.rstrip("\n").split("\n")


def body(lines: list[str], ranges) -> list[str]:
    if ranges is None:
        return lines
    out: list[str] = []
    for i, (a, b) in enumerate(ranges):
        if i or a > 1:
            out.append("// ...")
        out.extend(lines[a - 1:b])
    if ranges[-1][1] < len(lines):
        out.append("// ...")
    return out


def render() -> str:
    parts = [INTRO]
    for ident, lang, path, ranges, caption in LISTINGS:
        code = "\n".join(body(source(path), ranges))
        parts.append(f'\nДалі наведено файл `{path}` (лістинг @{ident}).\n\n'
                     f'```{{#{ident} .{lang} caption="{caption}"}}\n{code}\n```\n')
    return "".join(parts)


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != content:
            print(f"{OUT.name} is stale: run thesis/tools/appendix.py")
            return 1
        return 0
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT.relative_to(THESIS)}: {content.count(chr(10))} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
