#!/usr/bin/env python3
"""Number the sources of thesis/sources.yaml in order of first citation and write the
СПИСОК ВИКОРИСТАНИХ ДЖЕРЕЛ (chapters/95-references.md).

Citations are pandoc-style groups in the chapters: [@a], [@a; @b], [@a, с. 15]. Cross-reference
prefixes (fig:, tbl:, lst:, eq:, sc:) are not sources. Code (fenced blocks and `inline`) is ignored.
Order = lexical order of chapters/*.md (the build order), first occurrence wins (Regulations §6.9).

The output is a preview and a fallback: tools/thesis.lua numbers [@key] citations and fills the
#refs div itself in the same order. Run --check before committing chapter changes.

Usage (from repo root):
  python3 thesis/tools/references.py            # rewrite chapters/95-references.md
  python3 thesis/tools/references.py --check    # exit 1 if a key is unresolved, a source is duplicated
                                                # or uncited, or 95-references.md is stale
  python3 thesis/tools/references.py --map      # print "n<TAB>key" (the numbering the Lua filter must use)
"""
import json
import re
import sys
from pathlib import Path

THESIS = Path(__file__).resolve().parent.parent
CHAPTERS = THESIS / "chapters"
OUT = CHAPTERS / "95-references.md"
XREF = ("fig:", "tbl:", "lst:", "eq:", "sc:")
GROUP = re.compile(r"\[([^\[\]]*@[^\[\]]*)\]")
KEY = re.compile(r"@([A-Za-z0-9][A-Za-z0-9_.:-]*[A-Za-z0-9])")
HEADER = "# СПИСОК ВИКОРИСТАНИХ ДЖЕРЕЛ\n"
NOTE = ("<!-- Generated by thesis/tools/references.py from sources.yaml in order of first citation. "
        "Do not edit by hand: add sources to sources.yaml and re-run the script. The list sits in the "
        "#refs div, which tools/thesis.lua replaces with its own list (same order), so the build never "
        "duplicates it. -->\n")


def load_sources() -> list[tuple[str, str]]:
    entries, key = [], None
    for n, line in enumerate((THESIS / "sources.yaml").read_text(encoding="utf-8").splitlines(), 1):
        if m := re.match(r"^\s*- key:\s*(\S+)\s*$", line):
            key = m.group(1)
        elif m := re.match(r'^\s*text:\s*(".*")\s*$', line):
            if key is None:
                sys.exit(f"sources.yaml:{n}: text without key")
            entries.append((key, json.loads(m.group(1))))
            key = None
    return entries


def strip_code(text: str) -> str:
    text = re.sub(r"^```.*?^```", "", text, flags=re.S | re.M)
    return re.sub(r"`[^`\n]*`", "", text)


def cited_keys() -> list[tuple[str, str]]:
    """(key, file) in order of first citation."""
    seen: dict[str, str] = {}
    for path in sorted(CHAPTERS.glob("*.md")):
        if path == OUT:
            continue
        for group in GROUP.findall(strip_code(path.read_text(encoding="utf-8"))):
            for key in KEY.findall(group):
                if not key.startswith(XREF):
                    seen.setdefault(key, path.name)
    return list(seen.items())


def url_of(text: str) -> str | None:
    m = re.search(r"URL:\s*(\S+)", text)
    return m.group(1).rstrip(".") if m else None


def render(order: list[str], texts: dict[str, str]) -> str:
    lines = [HEADER, NOTE, "::: {#refs}"]
    for n, key in enumerate(order, 1):
        lines.append(f"{n}. " + texts[key].replace("@", "\\@") + "\n")
    lines.append(":::\n")
    return "\n".join(lines)


def main() -> int:
    entries = load_sources()
    texts = dict(entries)
    errors, warnings = [], []
    keys = [k for k, _ in entries]
    for k in {k for k in keys if keys.count(k) > 1}:
        errors.append(f"duplicate key in sources.yaml: {k}")
    by_url: dict[str, str] = {}
    for k, t in entries:
        u = url_of(t)
        if u and u in by_url:
            errors.append(f"same URL under two keys: {by_url[u]}, {k} ({u})")
        elif u:
            by_url[u] = k
    cited = cited_keys()
    for k, f in cited:
        if k not in texts:
            errors.append(f"{f}: [@{k}] has no entry in sources.yaml")
    order = [k for k, _ in cited if k in texts]
    for k in keys:
        if k not in order:
            warnings.append(f"uncited source (not listed): {k}")
    if "--map" in sys.argv:
        for n, k in enumerate(order, 1):
            print(f"{n}\t{k}")
        return 0
    content = render(order, texts)
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != content:
            errors.append(f"{OUT.name} is stale: run thesis/tools/references.py")
    else:
        OUT.write_text(content, encoding="utf-8")
    for w in warnings:
        print("warning:", w)
    for e in errors:
        print("error:", e)
    print(f"{len(order)} sources cited, {len(entries)} in sources.yaml")
    return 1 if errors or ("--check" in sys.argv and warnings) else 0


if __name__ == "__main__":
    sys.exit(main())
