@startuml
!pragma layout smetana
skinparam defaultFontName "Liberation Serif"
skinparam dpi 200
skinparam shadowing false
skinparam monochrome true
skinparam defaultFontSize 12
skinparam packageStyle rectangle
left to right direction

actor "Глядач" as Viewer
actor "Стример" as Streamer
actor "Google" as Google <<зовнішня система>>

Streamer -|> Viewer

rectangle "Вебсервіс трансляції медіаконтенту" {
  usecase UC_SignIn as "Авторизація через Google
--
точки розширення:
перший вхід"
  usecase "Реєстрація" as UC_SignUp
  usecase "Перегляд трансляції" as UC_Watch
  usecase "Трансляція у браузері" as UC_Browser
  usecase "Трансляція окремого\nзастосунку" as UC_App
  usecase "Завершення трансляції" as UC_End
}

Viewer --> UC_SignIn
Viewer --> UC_Watch
UC_SignIn --> Google
UC_SignIn <.. UC_SignUp : <<extend>>

Streamer --> UC_Browser
Streamer --> UC_App
Streamer --> UC_End
@enduml
